var quotes = [
'I believe in you.',
'What could you do differently next time?',
'It sounds like this crossed a boundary for you.',
'I can tell that you\'re giving it you\'re best effort.',
'I can hear how difficult this is for you.',
'You\'ve got this!',
'It\'s understandable that you\'re responding this way.',
'Can you tell me more about that?',
'What does a next step look like for you?',
'I\'m glad you told me.',
'What are some good things about the situation?',
'In what ways is this important to you?',
'You\'re right, it totally just sucks.',
'You\'re allowed to feel this way.',
'Let\'s take a pause and drink some water.',
'You\'re making total sense.',
'I\'m with you.',
'No wonder you\'re upset.',
'What is giving you energy today?',
'That sounds frustrating.',
'Tell me what you see as your choices here.',
'How might you free yourself from this?',
'Wow, that must have hurt.',
'I\'m so excited for you!',
'You deserve to be celebrated.',
'I wish I had been there with you when that happened.',
'Thank you for trusting me with this.',
'I would have a hard time with that too.',
'OK, how are we celebrating?!',
'Yes, you did!',
'I\'m so proud of you!',
'I miss you too.',
'It\'s OK, not to be OK.',
'What does rest look like for you today?',
'How are you moving your body today?',
'My heart hurts for you.',
'I can\'t imagine what you must be going through.',
'Thank you for sharing with me.',
'What has this been like for you?',
'You matter.',
'I\'m here for you.',
'This is a difficult situation and I think you\'ve shown courage and strength in how you\'re handling things.',
]

function newQuote() {
	var randomNumber = Math.floor(Math.random() * (quotes.length));
	document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}
