var quotes = [
'I believe in you.',
'What could you do differently next time?',
'It sounds like this crossed a boundary for you.',
'I can tell that you\'re giving it you\'re best effort.',
'I can hear how difficult this is for you.',
'It\'s understandable that you\'re responding this way.',
'Can you tell me more about that?',
'What does a next step look like for you?',
'I\'m glad you told me.',
'In what ways is this important to you?',
'You\'re right, it totally just sucks.',
'You\'re allowed to feel this way.',
'Let\'s take a pause and drink some water.',
'You\'re making total sense.',
'I\'m with you.',
'No wonder you\'re upset.',
'What is giving you energy today?',
'That sounds frustrating.',
'Tell me what you see as your choices here.',
'How might you free yourself from this?',
'Wow, that must have hurt.',
'You deserve to be heard.',
'I wish I had been there with you when that happened.',
'Thank you for trusting me with this.',
'I would have a hard time with that too.',
'It\'s OK, not to be OK.',
'What does rest look like for you today?',
'How are you moving your body today?',
'My heart hurts for you.',
'I can\'t imagine what you must be going through.',
'Thank you for sharing with me.',
'What has this been like for you?',
'You matter.',
'I\'m here for you.',
'This is a difficult situation and I think you\'ve shown courage and strength in how you\'re handling things.',
'I\'m sorry you\'re going through this.',
'I hate that this happened.',
'That sounds really challenging.',
'I can see how that would be difficult.',
'Thank you for sharing with me.',
'I\'m glad you told me.',
'Thank you for trusting me with this.',
'This must be hard to talk about. Thanks for opening up to me.',
'Thanks for letting me celebrate with you.',
'How are you feeling about everything?',
'What has this been like for you?',
'I want to make sure I understand...',
'Is there anything else you want to share?',
'You matter.',
'I\'m proud of you.',
'I\'m here for you.',
'What do you need right now?',
'I would like to do _______ for you.',
'This is a difficult situation and I think you\'ve shown a ton of courage and strength in how you\'re handling things.',
'What do you think would help you feel better?',
'What would be most helpful to you right now?',
'How are you feeling today?',
'It\'s totally natural that you would feel this way.',
'I can see how hard you tried here.',
'So, what I hear you saying is...',
'What I\'m hearing is that you are feeling _______ is that right?',
'I\'m glad you told me.',
'This must be hard to talk about. Thanks for opening up to me.',
'What I\'m hearing is...',
'It sounds like...',
'It seems like...',
'It can be really _______ when _______.',
'That sounds _______.',
'You are making a lot of sense to me.',
'What I admire most about what you\'re doing is...',
'I can see how...',
'You\'re not alone in this. I\'m here for you.',
'What you\'re feeling is valid.',
'I can see how dealing with this might be...',
'What you just said really helps me understand the situation better.',
'Tell me more...',
'Can you say more about that?',
'Can you share with me what ________ might look like?',
]

function newQuote() {
	var randomNumber = Math.floor(Math.random() * (quotes.length));
	document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}
